In [59]:
import torch

In [60]:
x = torch.arange(12)

In [61]:
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


#### 这里没有（）

In [62]:
print(x.shape)

torch.Size([12])


In [63]:
print(x.size())

torch.Size([12])


### number of element

In [64]:
print(x.numel())

12


In [65]:
print(x.reshape(3,4))

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [66]:
print(x.reshape(-1,2))

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])


### 这个按列堆叠、按行堆叠到后面可能会用到

In [67]:
x = torch.arange(12,dtype=torch.float32).reshape((3,4))
y = torch.tensor([[2.0, 1, 4, 4], [1, 2, 3, 4], [4, 3, 2, 1]])
a = torch.cat((x, y), dim=0) # 按列堆叠
b = torch.cat((x, y), dim=1) # 按行堆叠
a,b

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  4.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  4.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [68]:
x.sum()

tensor(66.)

### pandas的学习

In [69]:
import os
import pandas as pd

os.makedirs(os.path.join("data01"), exist_ok=True)
data_file = os.path.join("data01","house_timy.csv")
with open(data_file, 'w') as f:
    f.write('NumRooms, Alley, Price\n')
    f.write('NA,Pave, 127500\n')
    f.write('2,NA,10600\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [70]:
import pandas as pd
data = pd.read_csv(data_file)
print(data)

   NumRooms  Alley   Price
0       NaN   Pave  127500
1       2.0    NaN   10600
2       4.0    NaN  178100
3       NaN    NaN  140000


In [71]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
num_cols = inputs.select_dtypes(include='number').columns
inputs[num_cols] = inputs[num_cols].fillna(inputs[num_cols].mean())


inputs = pd.get_dummies(inputs, dummy_na=True)
inputs

NumRooms   Alley_Pave   Alley_nan
0       3.0            1           0
1       2.0            0           1
2       4.0            0           1
3       3.0            0           1

In [72]:
# 将csv文件转换为tensor文件
x, y = torch.tensor(inputs.values), torch.tensor(outputs.values)
x, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500,  10600, 178100, 140000]))

### 矩阵的转置

In [73]:
A = torch.arange(16).reshape(4, 4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [74]:
A.T

tensor([[ 0,  4,  8, 12],
        [ 1,  5,  9, 13],
        [ 2,  6, 10, 14],
        [ 3,  7, 11, 15]])

In [75]:
A == A.T

tensor([[ True, False, False, False],
        [False,  True, False, False],
        [False, False,  True, False],
        [False, False, False,  True]])

### 关于channel的解释

In [76]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

### 向量的加法

In [82]:
import torch
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

### 哈达玛积

In [ ]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

: 